import = [
    "~/.config/alacritty/themes/challenger_deep.toml",
    "~/.config/alacritty/bindings.toml",
]

[env]
TERM = 'alacritty'

[font]
size = 14

[window]
decorations = "full"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[font.offset]
x = 0
y = 1

[window.dimensions]
columns = 90
lines = 28
